apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-rust-api
  title: Demo Rust API
  description: A demo REST API built with Rust and Axum framework
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: alessandro/demo-rust-api
  tags:
    - rust
    - api
    - axum
    - demo
  links:
    - url: http://localhost:3030/health
      title: Health Check
      icon: dashboard
    - url: http://localhost:3030/api/v1/items
      title: API Endpoint
      icon: code
spec:
  type: service
  lifecycle: experimental
  owner: guests
  providesApis:
    - demo-rust-api-v1
